secret: "{{secret}}"
# port: 7890
# socks-port: 7891
mixed-port: 7890
allow-lan: {{allow_lan}}
{% if allow_lan %}
bind-address: '{{ansible_default_ipv4.address}}'
{% else %}
bind-address: '127.0.0.1'
{% endif %}
mode: rule
log-level: info
external-controller: {{external_controller}}
dns:
  enable: true
  listen: 0.0.0.0:5353
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  # enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp

{% if cfg_subscribes %}
proxy-providers:
  {%- for subscribe in cfg_subscribes +%}
{{ subscribe.name | indent(2, true) }}:
    type: http
    url: "{{subscribe.url}}"
    interval: 600
    path: "{{conf_dir}}/{{subscribe.name}}-subscribe.yaml"
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204
   {% endfor %}
{% endif %}