- name: gen client config
  template:
    src: "{{item}}"
    dest: "{{CONSUL_CONFIG_DIR}}/{{item}}"
  loop:
    - agent-gossip-encryption.hcl
    - agent-client-acl-tokens.hcl
    - agent-client-secure.hcl
  notify:
    - restart consul

- name: "gen svc {{cli.service.name}} config"
  when: cli.service
  template:
    src: "svc.hcl"
    dest: "{{CONSUL_CONFIG_DIR}}/svc-{{cli.service.name}}.hcl"

- name: copy agent ca pem
  copy:
    src: "{{playbook_dir}}/consul-agent-ca.pem"
    dest: "{{CONSUL_CONFIG_DIR}}/consul-agent-ca.pem"

- name: "Validate configuration"
  shell: |
    consul validate {{CONSUL_CONFIG_DIR}}  

- name: ensure home dir owner and group
  file:
    path: "{{home}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
    recurse: yes

- name: "start and enable {{systemd_name}} systemd service"
  systemd:
    name: "{{systemd_name}}"
    state: started
    enabled: true
    daemon_reload: true

###
- name: "install jq"
  copy:
    src: "jq-linux64"
    dest: /usr/local/bin/jq
    mode: '0755'

- name: consul bash profile add
  blockinfile:
    path: "~/.bash_profile"
    block: |
      export CONSUL_HTTP_ADDR="{{CONSUL_HTTP_ADDR}}"
      export CONSUL_HTTP_SSL="{{CONSUL_HTTP_SSL|lower}}"
      export CONSUL_CACERT="{{CONSUL_CACERT}}"
      export CONSUL_TLS_SERVER_NAME="{{CONSUL_TLS_SERVER_NAME}}"
      export CONSUL_HTTP_TOKEN="{{CONSUL_HTTP_TOKEN}}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for consul client"

- name: ensure home dir owner and group
  file:
    path: "{{home}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
    recurse: yes