---
- name: check if downloaded
  stat:
    path: "{{download_dest}}"
  register: downloaded

- name: "Download {{systemd_name}}"
  when: not downloaded.stat.exists
  get_url:
    url: "{{urlpath}}"
    dest: "{{download_dest}}"

- name: create temp dir
  tempfile:
    state: directory
  register: tempdir

- name: unarchive
  unarchive:
    src: "{{download_dest}}"
    dest: "{{tempdir.path}}"
    remote_src: yes

- name: user create
  user:
    name: "{{user}}"
    state: present

- name: group create
  group:
    name: "{{group}}"
    state: present

- name: ensure home and relavtive dirs created
  file:
    path: "{{item}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
  loop:
    - "{{home}}"
    - "{{CONSUL_DATA_DIR}}"
    - "{{CONSUL_CONFIG_DIR}}"
    - "{{CONSUL_TOKEN_DIR}}"
    - "{{CONSUL_POLICY_DIR}}"

- name: sync to home dir
  ansible.posix.synchronize:
    src: "{{tempdir.path}}/"
    dest: "{{home}}/"
  delegate_to: "{{ inventory_hostname }}"

- name: ensure home dir owner and group
  file:
    path: "{{home}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
    recurse: yes

- name: clean temp dir
  when: tempdir is defined
  file:
    path: "{{tempdir.path}}"
    state: absent

- name: create systemd unit file
  template:
    src: "{{systemd_name}}.service"
    dest: "/etc/systemd/system/{{systemd_name}}.service"

- name: add {{systemd_name}} shortcuts commands
  blockinfile:
    path: "~/.bash_profile"
    marker: "# {{item}} {mark} ANSIBLE MANAGED BLOCK"
    block: |
      alias {{item}}status='systemctl status {{item}}.service'
      alias {{item}}start='systemctl start {{item}}.service'
      alias {{item}}stop='systemctl stop {{item}}.service'
      alias {{item}}restart='systemctl restart {{item}}.service'
    create: true
  loop:
    - "{{systemd_name}}"


- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{home}}/{{systemd_name}}"
    dest: "/usr/bin/{{systemd_name}}"
    owner: "{{user}}"
    group: "{{group}}"
    state: link

- name: gen config
  template:
    src: "{{item}}"
    dest: "{{CONSUL_CONFIG_DIR}}/{{item}}"
  loop:
    - agent-server-secure.hcl
    - agent-server-specific.hcl
    - agent-server-tls.hcl
    - agent-server-acl.hcl

- name: "Generate gossip encryption key configuration - agent-gossip-encryption.hcl"
  shell: |
    echo encrypt = \"$(consul keygen)\" > {{CONSUL_CONFIG_DIR}}/agent-gossip-encryption.hcl
  args:
    chdir: "{{CONSUL_CONFIG_DIR}}"

- name: "Create CA for Consul datacenter"
  shell: |
    consul tls ca create -domain={{DOMAIN}}
  args:
    chdir: "{{CONSUL_CONFIG_DIR}}"
    creates: "{{DOMAIN}}-agent-ca.pem"

- name: "Create server Certificate and key pair"
  shell: |
    consul tls cert create -server -domain {{DOMAIN}} -dc={{DATACENTER}}
  args:
    chdir: "{{CONSUL_CONFIG_DIR}}"
    creates: "{{DATACENTER}}-server-{{DOMAIN}}-0.pem"

- name: "Validate configuration"
  shell: |
    consul validate {{CONSUL_CONFIG_DIR}}  

- name: ensure home dir owner and group
  file:
    path: "{{home}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
    recurse: yes

- name: "start and enable {{systemd_name}} systemd service"
  systemd:
    name: "{{systemd_name}}"
    state: started
    enabled: true
    daemon_reload: true

###
- name: "install jq"
  copy:
    src: "jq-linux64"
    dest: /usr/local/bin/jq
    mode: '0755'

- name: "get management token"
  shell: |
      if [[ ! -e "acl-token-bootstrap.json" ]];then
        consul acl bootstrap --format json > acl-token-bootstrap.json
      fi
  args:
    chdir: "{{CONSUL_TOKEN_DIR}}"
    creates: acl-token-bootstrap.json

- name: register SecretID
  shell: |
    jq -r ".SecretID" acl-token-bootstrap.json
  args:
    chdir: "{{CONSUL_TOKEN_DIR}}"
  register: SecretID
  
- name: "export token in bash_profile"
  lineinfile:
    path: ~/.bash_profile
    line: "export CONSUL_HTTP_TOKEN=\"{{SecretID.stdout}}\""

- name: Create the policy files
  block:
  - name: generate policy file
    template:
      src: "{{item}}"
      dest: "{{CONSUL_POLICY_DIR}}/{{item}}"
    loop:
      - "acl-policy-dns.hcl"
      - "acl-policy-server-node.hcl"
  - name: "apply policy to consul server"
    shell: |      
      p1=$(consul acl policy list -format=json | jq -r '.[] | select(.Name == "acl-policy-dns").Name')
      if [[ "$p1" != "acl-policy-dns"  ]];then
        consul acl policy create -name 'acl-policy-dns' -description 'Policy for DNS endpoints' -rules @./acl-policy-dns.hcl
      fi

      p2=$(consul acl policy list -format=json | jq -r '.[] | select(.Name == "acl-policy-server-node").Name')
      if [[ "$p2" != "acl-policy-server-node"  ]];then
        consul acl policy create -name 'acl-policy-server-node' -description 'Policy for Server nodes' -rules @./acl-policy-server-node.hcl
      fi
    args:
      chdir: "{{CONSUL_POLICY_DIR}}"
    environment:
      CONSUL_HTTP_TOKEN: "{{SecretID.stdout}}"


- name: "Create ACL tokens for each policy"
  shell: |
    if [ ! -s "{{CONSUL_TOKEN_DIR}}/acl-token-dns.json" ];then
      consul acl token create -description 'DNS - Default token' -policy-name acl-policy-dns --format json > {{CONSUL_TOKEN_DIR}}/acl-token-dns.json
    fi
    if [ ! -s "{{CONSUL_TOKEN_DIR}}/acl-token-server.json" ];then
      consul acl token create -description "server agent token" -policy-name acl-policy-server-node  --format json > {{CONSUL_TOKEN_DIR}}/acl-token-server.json
    fi
  args:
    chdir: "{{CONSUL_TOKEN_DIR}}"
  environment:
    CONSUL_HTTP_TOKEN: "{{SecretID.stdout}}"

- name: "Assign tokens to the server agent"
  shell: |
    consul acl set-agent-token default $(jq -r ".SecretID" acl-token-dns.json)
    consul acl set-agent-token agent $(jq -r ".SecretID" acl-token-server.json)
  args:
    chdir: "{{CONSUL_TOKEN_DIR}}"
  environment:
    CONSUL_HTTP_TOKEN: "{{SecretID.stdout}}"

- name: ensure home dir owner and group
  file:
    path: "{{home}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
    recurse: yes
      

