- name: gen config
  template:
    src: "{{item}}"
    dest: "{{CONSUL_CONFIG_DIR}}/{{item}}"
  loop:
    - agent-server-secure.hcl
    - agent-server-specific.hcl
    - agent-server-tls.hcl
    - agent-server-acl.hcl

- name: "Generate gossip encryption key configuration - agent-gossip-encryption.hcl"
  shell: |
    echo encrypt = \"$(consul keygen)\" > {{CONSUL_CONFIG_DIR}}/agent-gossip-encryption.hcl
  args:
    chdir: "{{CONSUL_CONFIG_DIR}}"

- name: "Create CA for Consul datacenter"
  shell: |
    consul tls ca create -domain={{DOMAIN}}
  args:
    chdir: "{{CONSUL_CONFIG_DIR}}"
    creates: "{{DOMAIN}}-agent-ca.pem"

- name: "Create server Certificate and key pair"
  shell: |
    consul tls cert create -server -domain {{DOMAIN}} -dc={{DATACENTER}}
  args:
    chdir: "{{CONSUL_CONFIG_DIR}}"
    creates: "{{DATACENTER}}-server-{{DOMAIN}}-0.pem"

- name: "Validate configuration"
  shell: |
    consul validate {{CONSUL_CONFIG_DIR}}  

- name: ensure home dir owner and group
  file:
    path: "{{home}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
    recurse: yes

- name: "start and enable {{systemd_name}} systemd service"
  systemd:
    name: "{{systemd_name}}"
    state: started
    enabled: true
    daemon_reload: true

###
- name: "install jq"
  copy:
    src: "jq-linux64"
    dest: /usr/local/bin/jq
    mode: '0755'

- name: "get management token"
  shell: |
      if [[ ! -e "acl-token-bootstrap.json" ]];then
        consul acl bootstrap --format json > acl-token-bootstrap.json
      fi
  args:
    chdir: "{{CONSUL_TOKEN_DIR}}"
    creates: acl-token-bootstrap.json

- name: register SecretID
  shell: |
    jq -r ".SecretID" acl-token-bootstrap.json
  args:
    chdir: "{{CONSUL_TOKEN_DIR}}"
  register: SecretID
  
- name: "export token in bash_profile"
  lineinfile:
    path: ~/.bash_profile
    line: "export CONSUL_HTTP_TOKEN=\"{{SecretID.stdout}}\""

- name: Create the policy files
  block:
  - name: generate policy file
    template:
      src: "{{item}}"
      dest: "{{CONSUL_POLICY_DIR}}/{{item}}"
    loop:
      - "acl-policy-dns.hcl"
      - "acl-policy-server-node.hcl"
  - name: "apply policy to consul server"
    shell: |      
      p1=$(consul acl policy list -format=json | jq -r '.[] | select(.Name == "acl-policy-dns").Name')
      if [[ "$p1" != "acl-policy-dns"  ]];then
        consul acl policy create -name 'acl-policy-dns' -description 'Policy for DNS endpoints' -rules @./acl-policy-dns.hcl
      fi

      p2=$(consul acl policy list -format=json | jq -r '.[] | select(.Name == "acl-policy-server-node").Name')
      if [[ "$p2" != "acl-policy-server-node"  ]];then
        consul acl policy create -name 'acl-policy-server-node' -description 'Policy for Server nodes' -rules @./acl-policy-server-node.hcl
      fi
    args:
      chdir: "{{CONSUL_POLICY_DIR}}"
    environment:
      CONSUL_HTTP_TOKEN: "{{SecretID.stdout}}"


- name: "Create ACL tokens for each policy"
  shell: |
    if [ ! -s "{{CONSUL_TOKEN_DIR}}/acl-token-dns.json" ];then
      consul acl token create -description 'DNS - Default token' -policy-name acl-policy-dns --format json > {{CONSUL_TOKEN_DIR}}/acl-token-dns.json
    fi
    if [ ! -s "{{CONSUL_TOKEN_DIR}}/acl-token-server.json" ];then
      consul acl token create -description "server agent token" -policy-name acl-policy-server-node  --format json > {{CONSUL_TOKEN_DIR}}/acl-token-server.json
    fi
  args:
    chdir: "{{CONSUL_TOKEN_DIR}}"
  environment:
    CONSUL_HTTP_TOKEN: "{{SecretID.stdout}}"

- name: "Assign tokens to the server agent"
  shell: |
    consul acl set-agent-token default $(jq -r ".SecretID" acl-token-dns.json)
    consul acl set-agent-token agent $(jq -r ".SecretID" acl-token-server.json)
  args:
    chdir: "{{CONSUL_TOKEN_DIR}}"
  environment:
    CONSUL_HTTP_TOKEN: "{{SecretID.stdout}}"

- name: ensure home dir owner and group
  file:
    path: "{{home}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
    recurse: yes