---
# tasks file for n9e-v6.0.0

- name: remove home dir
  file:
    path: "{{home}}"
    state: absent

- name: remove systemd unit file
  file:
    path: "/etc/systemd/system/{{item}}.service"
    state: absent
  with_items:
    - "{{name}}"


- name: "remove {{name}} shortcuts commands"
  blockinfile:
    path: "~/.bash_profile"
    marker: "# {{item}} {mark} ANSIBLE MANAGED BLOCK"
    block: |
      alias {{item}}-status='systemctl status {{item}}.service'
      alias {{item}}-start='systemctl start {{item}}.service'
      alias {{item}}-stop='systemctl stop {{item}}.service'
      alias {{item}}-restart='systemctl restart {{item}}.service'
    create: true
    state: absent
  loop:
    - "{{name}}"