---
# vars file for consul-1.14.3
systemd_name: consul
uninstall: false
version: 1.14.3
zipfile: "consul_{{version}}_linux_amd64.zip"
urlpath: "https://releases.hashicorp.com/consul/{{version}}/{{zipfile}}"
download_dest: "/tmp/{{zipfile}}"
home: "/data/{{systemd_name}}/{{version}}"
user: consul
group: consul

CONSUL_DATA_DIR: "{{home}}/data"
CONSUL_CONFIG_DIR: "{{home}}/conf"
CONSUL_POLICY_DIR: "{{CONSUL_CONFIG_DIR}}/policies"
CONSUL_TOKEN_DIR: "{{CONSUL_CONFIG_DIR}}/tokens"
DATACENTER: dc1
DOMAIN: consul

# This is a unique name for the agent used as -node opt in startup command line
NODE_NAME: consul
# used for retry_join, for client find server
SERVER_NAME: consul
FQDN_SUFFIX: ""
CONSUL_HTTP_ADDR: "https://CONSUL_ADDRESS:8443"
CONSUL_HTTP_SSL: true
CONSUL_CACERT: "{{CONSUL_CONFIG_DIR}}/consul-agent-ca.pem"
CONSUL_TLS_SERVER_NAME: "server.{{DATACENTER}}.{{DOMAIN}}"
CONSUL_HTTP_TOKEN: ""
# server config template vars
# https://developer.hashicorp.com/consul/tutorials/production-deploy/deployment-guide#server-specific-configuration
config:
  #### agent-server-secure.hcl
  ## config generate relative
  data_dir: "{{CONSUL_DATA_DIR}}"
  # Enable service mesh
  connect:
    enabled: true
  addresses:
    grpc: 127.0.0.1
    https: 0.0.0.0
    dns: 0.0.0.0
  ports:
    grpc_tls: 8502
    http: 8500
    https: 8443
    dns: 8600
  # Disable script checks
  enable_script_checks: false
  # Enable local script checks
  enable_local_script_checks: true
  recursors: 
  - 1.1.1.1
  log_level: DEBUG

    
  #### agent-server-specific.hcl
  ## Server specific configuration
  # This flag is used to control if an agent is in server or client mode.
  server: true
  retry_join:
    - "{{SERVER_NAME}}"
  # Replace the bootstrap_expect value with the number of
  # Consul servers you will use; three or five is recommended.
  bootstrap_expect: 1
  datacenter: "dc1"
  # By default, Consul will bind on all available addresses 
  # on the machine and expose client interfaces only on localhost/127.0.0.1.
  client_addr: "127.0.0.1"
  # Consul agent will bind to all addresses on the local machine and will advertise the private IPv4 address to the rest of the datacenter.
  # There are some cases when you want to specify the bind address for your Consul server:
  # - the Consul node has multiple private IP addresses available
  # - the Consul node has only public IP addresses available
  # If there are multiple private IPv4 addresses available, Consul will exit with an error at startup:
  # Multiple private IPv4 addresses found. Please configure one with 'bind' and/or 'advertise'.
  # To prevent this from happening it is possible to define on which address Consul will bind using the bind_addr parameter.
  # bind_addr: "172.16.0.10"
  
  ## UI configuration (1.9+)
  ui_config:
    enabled: true


  performance:
    raft_multiplier: 1



  encrypt: "gossip"

  service:
    name: demo
    id: "{{config.service.name}}-1"
    tags: ["v1"]
    port: 8080
    check:
      id: "check-{{config.service.name}}"
      name: "Product {{config.service.name}} status check"
      service_id: "{{config.service.name}}-1"
      tcp: "localhost:8080"
      interval: "1s"
      timeout: "1s"