---
- name: stop  service
  systemd:
    name: "{{systemd_name}}"
    state: stopped

- name: remove systemd unit file
  file:
    path: "{{item}}/{{systemd_name}}.service"
    state: absent
  loop:
  - "/etc/systemd/system"
  - "/lib/systemd/system"
  - "/usr/lib/systemd/system"

- name: remove home dir
  file:
    path: "{{home}}"
    state: absent
