# 需要卸载应用时，通过命令行传递这个变量
# ansible-playbook pb.yaml -e uninstall=true
uninstall: false
# 是否跳过handler执行，默认配置修改后会通知handler完成服务重启，
# 可以通过设置为True来跳过handler执行
skip_handlers: false
user: app_user
group: app_group
# define service state after deloy
# possible values: started, stopped, restarted, reloaded
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html#parameter-state
service_state: started

systemd_name: "elasticsearch"
# used for service ctl alias commands
# for example {{systemd_name_short}}status -> systemctl status {{systemd_name}}.service
systemd_short_name: "es"
version: 7.17.22

archive_file: "elasticsearch-{{version}}-linux-x86_64.tar.gz"
download_dest: "/tmp/{{archive_file}}"
unpacked_dirname: elasticsearch-{{version}}
home: "/data/elasticsearch/{{version}}"
# define ExecStart and ExecStop in systemd unit file
exec_start: "{{home}}/bin/elasticsearch"
exec_stop: ""
# systemd restart policy
systemd_restart: "on-failure"
home_subdirs: []

# 拷贝额外文件到远程主机，一般不需要
file_copies: []
# file_copies:
# - src: jmx_prometheus_javaagent-0.18.0.jar
#   dest: "{{home}}/bin/jmx_prometheus_javaagent-0.18.0.jar"
config_files:
- src: systemd.service
  dest: /etc/systemd/system/{{systemd_name}}.service
- src: "env"
  dest: "{{home}}/.env"
- src: heapsize.options
  dest: "{{home}}/config/jvm.options.d/heapsize.options"
- src: elasticsearch.yml
  dest: "{{home}}/config/elasticsearch.yml"


# cluster deploy control
bootstrap: false
httptls_sync: false
httpssl: false
start: start
# 请在host_vars目录为主机设置此变量
#node_roles: ['ca', 'master']

# ENV
ES_JAVA_OPTS: ""

# custom jvm options
## head size
jvm_opt_xms: 2g
jvm_opt_xmx: 2g

## elasticsearch.yml
# xpack.security.enabled
xpack_security_enabled: false
# cluster.name
cluster_name: "elasticsearch"
# action.auto_create_index
action_auto_create_index: .monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*
