---
- name: "ensure {{SYSTEMD_NAME}} home dir exists"
  ansible.builtin.file:
    path: "{{HOME}}"
    state: directory
    mode: '0755'
    owner: "{{USER}}"
    group: "{{GROUP}}"

- name: "Check if {{DOWNLOAD_DEST}} already exists"
  stat:
    path: "{{DOWNLOAD_DEST}}"
  register: file_status

- name: Get {{SYSTEMD_NAME}} from S3
  when: not file_status.stat.exists
  shell: "aws s3 cp {{S3_URL}} {{DOWNLOAD_DEST}}"

- name: "Check if bin dir already exists"
  stat:
    path: "{{BINDIR}}"
  register: bin

- name: unarchive {{SYSTEMD_NAME}} package to home
  when: not bin.stat.exists
  block:
    - name: Create temporary directory
      tempfile:
        state: directory
      register: temp_dir

    - name:  unzip {{SYSTEMD_NAME}} to temp_dir
      ansible.builtin.unarchive:
        src: "{{DOWNLOAD_DEST}}"
        dest: "{{temp_dir.path}}"
        remote_src: yes

    - name: Sync fresh {{SYSTEMD_NAME}} to home dir
      synchronize:
        src: "{{temp_dir.path}}/{{UNARCHIVE_DIR}}/"
        dest: "{{HOME}}/"
        recursive: yes
      delegate_to: "{{ inventory_hostname }}"

    - name: del temp dir
      file:
        path: "{{temp_dir.path}}"
        state: absent
### Unit Files  
- name: zk unit
  template:
    src: zk.unit
    dest: "{{SYSTEMD_UNIT_ZK}}"
    owner: "{{USER}}"
    group: "{{GROUP}}"
    mode: 0644

- name: kafka unit
  template:
    src: kafka.unit
    dest: "{{SYSTEMD_UNIT}}"
    owner: "{{USER}}"
    group: "{{GROUP}}"
    mode: 0644


## Configfile
- name: "render {{item}}.properties"
  template:
    src: "{{item}}.properties"
    dest: "{{HOME}}/config/{{item}}.properties"
    owner: "{{USER}}"
    group: "{{GROUP}}"
    mode: 0644
  with_items:
    - server
    - zookeeper

- name: "ensure {{SYSTEMD_NAME}} home dir owner"
  ansible.builtin.file:
    path: "{{HOME}}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: "{{USER}}"
    group: "{{GROUP}}"

## Sudo Rules
- name: Add sudo start rule
  lineinfile:
    dest: /etc/sudoers
    insertafter: EOF
    line: '{{USER}} ALL=(ALL) NOPASSWD: /usr/bin/systemctl start {{item}}'
    validate: '/usr/sbin/visudo -cf %s'
    state: present
    backup: yes
  with_items:
    - "{{SYSTEMD_NAME}}"
    - "{{SYSTEMD_NAME_ZK}}"

- name: Add sudo stop rule
  lineinfile:
    dest: /etc/sudoers
    insertafter: EOF
    line: '{{USER}} ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop {{item}}'
    validate: '/usr/sbin/visudo -cf %s'
    state: present
    backup: yes
  with_items:
    - "{{SYSTEMD_NAME}}"
    - "{{SYSTEMD_NAME_ZK}}"
- name: Add sudo restart rule
  lineinfile:
    dest: /etc/sudoers
    insertafter: EOF
    line: '{{USER}} ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart {{item}}'
    validate: '/usr/sbin/visudo -cf %s'
    state: present
    backup: yes
  with_items:
    - "{{SYSTEMD_NAME}}"
    - "{{SYSTEMD_NAME_ZK}}"

- name: Add sudo status rule
  lineinfile:
    dest: /etc/sudoers
    insertafter: EOF
    line: '{{USER}} ALL=(ALL) NOPASSWD: /usr/bin/systemctl status {{item}}'
    validate: '/usr/sbin/visudo -cf %s'
    state: present
    backup: yes
  with_items:
    - "{{SYSTEMD_NAME}}"
    - "{{SYSTEMD_NAME_ZK}}"

## Alias for shortcut
- name: alias for zk service
  lineinfile:
    dest: "/home/{{USER}}/.bash_profile"
    insertafter: EOF
    line: "alias zk{{item}}='sudo /usr/bin/systemctl {{item}} {{SYSTEMD_NAME_ZK}}'"
    state: present
  with_items:
    - "start"
    - "stop"
    - "restart"
    - "status"

- name: alias for kafka service
  lineinfile:
    dest: "/home/{{USER}}/.bash_profile"
    insertafter: EOF
    line: "alias kfk{{item}}='sudo /usr/bin/systemctl {{item}} {{SYSTEMD_NAME}}'"
    state: present
  with_items:
    - "start"
    - "stop"
    - "restart"
    - "status"

## enable auto start service when reboot
- name: Enable service
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
    - "{{SYSTEMD_NAME}}"
    - "{{SYSTEMD_NAME_ZK}}"

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes
    