---
uninstall: false
systemd_name: consul
systemd_short_name: csl
version: 1.15.2
archive_file: "consul_{{version}}_linux_amd64.zip"
unpacked_dirname: ""
urlpath: "https://releases.hashicorp.com/consul/1.15.2/consul_1.15.2_linux_amd64.zip"
# set single_exec_deploy true only when deploy single executable file , normaly we deploy a zip, tgz or tar.gz etc.
single_exec_deploy: false
download_dest: "/tmp/{{archive_file}}"
home: "/data/{{systemd_name}}/{{version}}"
user: consul
group: consul
# define ExecStart and ExecStop in systemd unit file
exec_start: "{{home}}/consul agent -node={{node_name}} -config-dir={{home}}/conf/"
exec_stop: ""
# systemd restart policy
restart: "on-failure"

home_subdirs:
- "data"
- "conf/policies"
- "conf/tokens"
- "logs"
file_copies: []
# file_copies:
# - src: jmx_prometheus_javaagent-0.18.0.jar
#   dest: "{{home}}/bin/jmx_prometheus_javaagent-0.18.0.jar"

config_files:
- src: systemd.service
  dest: /etc/systemd/system/{{systemd_name}}.service

bootstrap: false
CONSUL_DATA_DIR: "{{home}}/data"
CONSUL_LOG_DIR: "{{home}}/logs"
CONSUL_CONFIG_DIR: "{{home}}/conf"
CONSUL_POLICY_DIR: "{{CONSUL_CONFIG_DIR}}/policies"
CONSUL_TOKEN_DIR: "{{CONSUL_CONFIG_DIR}}/tokens"
DATACENTER: korea
DOMAIN: consul

# server config template vars
# https://developer.hashicorp.com/consul/tutorials/production-deploy/deployment-guide#server-specific-configuration
#### agent-server-log.hcl
# The level of logging to show after the Consul agent has started. 
# This defaults to "info". The available log levels are "trace", "debug", "info", "warn", and "error".
log_level: info
log_file: "{{CONSUL_LOG_DIR}}/"
log_rotate_duration: "24h"
log_rotate_bytes: 0
# to specify the maximum number of older log file archives to keep.
log_rotate_max_files: 7
log_json: false
# This flag enables logging to syslog.
enable_syslog: false
syslog_facility: LOCAL0

#### agent-server-acl.hcl
default_token: ""
#### policies/acl-policy-server-node.hcl
node_prefix: ""
#### agent-server-specific.hcl
node_name: "{{inventory_hostname}}"
server: true
bootstrap_expect: 1
datacenter: "{{DATACENTER}}"
client_addr: "127.0.0.1"
ui_enabled: true

#### agent-server-secure.hcl
retry_join: ["{{ansible_default_ipv4.address}}"]
log_level: DEBUG
disable_keyring_file: true 
data_dir: "{{CONSUL_DATA_DIR}}"
connect_enabled: true
addresses_grpc: 127.0.0.1
addresses_http: 0.0.0.0
addresses_https: 0.0.0.0
addresses_dns: 0.0.0.0

ports_grpc_tls: 8502
ports_http: 8500
ports_https: 8443
ports_dns: 8600
# Disable script checks
enable_script_checks: false
# Enable local script checks
enable_local_script_checks: true
recursors: 
  - 1.1.1.1


  
# integration config
itgt_ngx_vh_enabled: false
itgt_ngx_vh_server_name: "consul.service.consul"
itgt_ngx_vh_port: 80
