---
# kafka
kafka_heap_opts: "-Xmx1G -Xms1G"
num_network_threads: 3
num_io_threads: 8
socket_send_buffer_bytes: 102400
socket_receive_buffer_bytes: 102400
socket_request_max_bytes: 104857600
num_recovery_threads_per_data_dir: 1
auto_create_topics_enable: true
transaction_state_log_min_isr: 1

log_retention_hours: 168
log_retention_bytes: 0

# zookeeper
useEmbededZk: true
zkDataDir: "{{home}}/zkDataDir"
zkDataLogDir: "{{home}}/zkDataLogDir"
zk_heap_opts: "-Xmx512m -Xms512m"
