---
- name: user create
  tags: ["deploy", "user"]
  user:
    name: "{{user}}"
    state: present

- name: group create
  tags: ["deploy", "group"]
  group:
    name: "{{group}}"
    state: present

- name: ensure home and relavtive dirs created
  tags: ["deploy", "home"]
  file:
    path: "{{item}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
  loop:
    - "{{home}}"

- name: Environement File
  tags: ["deploy", "env"]
  template:
    src: env
    dest: "{{home}}/.env"

- name: check if downloaded
  tags: ["deploy", "download"]
  stat:
    path: "{{download_dest}}"
  register: downloaded

- name: "Download"
  tags: ["deploy", "download"]
  when: not downloaded.stat.exists
  copy:
    src: "{{archive_file}}"
    dest: "{{download_dest}}"

- name: check if deployed already
  tags: ["deploy"]
  stat:
    path: "{{home}}/bin"
  register: deployed

- name: "Deploy"
  tags: ["deploy"]
  when: not deployed.stat.exists
  block:
  - name: create temp dir
    tempfile:
      state: directory
    register: r_tempdir

  - name: unarchive
    unarchive:
      src: "{{download_dest}}"
      dest: "{{r_tempdir.path}}"
      remote_src: yes

  - name: sync to home dir
    synchronize:
      src: "{{r_tempdir.path}}/kibana-{{version}}-linux-x86_64/"
      dest: "{{home}}/"
    delegate_to: "{{ inventory_hostname }}"

  - name: clean temp dir
    when: r_tempdir is defined
    file: 
      path: "{{r_tempdir.path}}"
      state: absent

- name: "Systemd Unit File"
  tags: ["deploy", "config", "systemd"]
  template:
    src: "{{item}}"
    dest: "/etc/systemd/system/{{item}}"
  loop:
  - "{{systemd_name}}.service"

- name: "Config Files"
  tags: ["deploy", "config", "kbnconfig"]
  template:
    src: "{{item}}"
    dest: "{{home}}/config/{{item}}"
  loop:
  - "kibana.yml"
  notify:
  - restart service

- name: Home Dir Owner And Group
  tags: ["deploy", "config", "ownergroup"]
  file:
    path: "{{home}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
    recurse: yes

- name: Sudoer Rules
  import_tasks: "{{role_path}}/tasks/sudorules.yml"

- name: Service Start
  tags: ["deploy", "start"]
  when: start
  systemd:
    name: "{{systemd_name}}"
    state: started
    enabled: true
    daemon_reload: true