- name: fetch http.p12
  tags: ["deploy", "tls", "httptls"]
  when: 
  - "'ca' in node_roles"
  - xpack_security_enabled
  - httpssl
  fetch:
    src: "{{home}}/elasticsearch-ssl-http.zip"
    dest: "{{playbook_dir}}/elasticsearch-ssl-http.zip"
    flat: true

- name: copy http cert to non-ca nodes
  tags: ["deploy", "tls", "httptls"]
  when:
  - xpack_security_enabled
  - httpssl
  block:
  - name: mktemp dir
    tempfile:
      state: directory
    register: temp_dir1

  - name: Unzip
    unarchive:
      src: "{{playbook_dir}}/elasticsearch-ssl-http.zip"
      dest: "{{temp_dir1.path}}/"
      owner: "{{user}}"
      group: "{{group}}"

  - name: Sync http.p12
    synchronize:
      src: "{{temp_dir1.path}}/elasticsearch/http.p12"
      dest: "{{home}}/config/http.p12"
    delegate_to: "{{inventory_hostname}}"
  
  - name: keep perm correct
    file:
      path: "{{home}}/config/http.p12"
      owner: "{{user}}"
      group: "{{group}}"

  - name: remove temp dir
    file:
      path: "{{temp_dir1.path}}"
      state: absent