---
- name: User Create
  user:
    name: "{{user}}"
    state: present

- name: Group Create
  group:
    name: "{{group}}"
    state: present

- name: Download
  block:
  - name: "Check If Downloaded"
    stat:
      path: "{{download_dest}}"
    register: downloaded
  - name: "Downloading"
    when: 
    - not downloaded.stat.exists
    copy:
      src: "{{archive_file}}"
      dest: "{{download_dest}}"
      owner: "{{user}}"
      group: "{{group}}"

- name: Deploy
  block:
  - name: Check if deployed already
    stat:
      path: "{{home}}/bin"
    register: deployed

  - name: Single Exec Deploy
    when:
    - single_exec_deploy
    - not deployed.stat.exists
    block:
    - name: "Home Dir"
      file:
        path: "{{home}}"
        state: directory
        owner: "{{user}}"
        group: "{{group}}"
    - name: Copy Single Exec File To Home
      copy:
        src: "{{download_dest}}"
        dest: "{{home}}/"
        owner: "{{user}}"
        group: "{{group}}"
        mode: u+x
        remote_src: true
    
  - name: "Package Deploy"
    when: 
    - not deployed.stat.exists
    - not single_exec_deploy
    block:
    - name: "Home Dir"
      file:
        path: "{{home}}"
        state: directory
        owner: "{{user}}"
        group: "{{group}}"

    - name: create temp dir
      tempfile:
        state: directory
      register: r_tempdir

    - name: unarchive
      unarchive:
        src: "{{download_dest}}"
        dest: "{{r_tempdir.path}}"
        remote_src: yes

    - name: sync to home dir
      synchronize:
        src: "{{r_tempdir.path}}/{{unpacked_dirname}}/"
        dest: "{{home}}/"
      delegate_to: "{{ inventory_hostname }}"

    - name: clean temp dir
      when: r_tempdir is defined
      file: 
        path: "{{r_tempdir.path}}"
        state: absent
  
  - name: "Sub Dir Under Home"
    file:
      path: "{{home}}/{{item}}"
      state: directory
      owner: "{{user}}"
      group: "{{group}}"
    loop: "{{home_subdirs}}"

- name: Ensure Home Dir Owner And Group
  file:
    path: "{{home}}"
    state: directory
    owner: "{{user}}"
    group: "{{group}}"
    recurse: yes

- name: bashrc enrich
  blockinfile:
    path: "/home/{{user}}/.bashrc"
    marker: "# {{systemd_name}} envs {mark} ANSIBLE MANAGED BLOCK"
    block: |
      export JAVA_HOME={{home}}
      export PATH=$JAVA_HOME/bin:$PATH
    create: true
    owner: "{{user}}"
    group: "{{group}}"