---
systemd_name: kafka
uninstall: false
scala_version: 2.12
version: 3.4.1
archive_file: "kafka_{{scala_version}}-{{version}}.tgz"
s3_url: "s3://upex-repository/middleware/kafka/{{archive_file}}"

urlpath: "https://archive.apache.org/dist/kafka/{{version}}/{{archive_file}}"
download_dest: "/tmp/{{archive_file}}"
home: "/data/{{systemd_name}}/{{scala_version}}-{{version}}"
# bk app user and group name
user: "app_user"
group: "app_group"
# install from files directory
install_from_files: false

java_home: /usr/lib/jvm/java-11-openjdk-amd64


# kafka
host_name: "{{inventory_hostname}}"
kafka_heap_opts: "-Xmx1G -Xms1G"
num_network_threads: 3
num_io_threads: 8
socket_send_buffer_bytes: 102400
socket_receive_buffer_bytes: 102400
socket_request_max_bytes: 104857600
num_recovery_threads_per_data_dir: 1
auto_create_topics_enable: true

log_retention_hours: 168
log_retention_bytes: 0

# zookeeper
useEmbededZk: false
zkDataDir: "{{home}}/zkDataDir"
zkDataLogDir: ""
zk_heap_opts: "-Xmx512m -Xms512m"
_4lw_commands_whitelist: "*"