---
cli_commands:
  - "kafka-acls"
  - "kafka-broker-api-versions"
  - "kafka-configs"
  - "kafka-console-consumer"
  - "kafka-console-producer"
  - "kafka-consumer-groups"
  - "kafka-consumer-perf-test"
  - "kafka-delegation-tokens"
  - "kafka-delete-records"
  - "kafka-dump-log"
  - "kafka-log-dirs"
  - "kafka-mirror-maker"
  - "kafka-preferred-replica-election"
  - "kafka-producer-perf-test"
  - "kafka-reassign-partitions"
  - "kafka-replica-verification"
  - "kafka-run-class"
  - "kafka-server-start"
  - "kafka-server-stop"
  - "kafka-streams-application-reset"
  - "kafka-topics"
  - "kafka-verifiable-consumer"
  - "kafka-verifiable-producer"
