---
- name: ensure nginx installed
  apt:
    pkg: 
     - nginx
     - apache2-utils

- name: create htpasswd file
  tags: ["createpassword"]
  shell: |
    htpasswd -b -c /etc/nginx/.htpasswd {{basic_auth_user}} {{basic_auth_password}}
  args:
    executable: /bin/bash
    
- name: Find my public ip
  uri: 
    url: http://ifconfig.me/ip
    return_content: yes
  register: ip_response 
- name: nginx vh config
  template:
    src: clash_dashboard.conf
    dest: /etc/nginx/sites-available/clash_dashboard.conf
  notify:
  - nginx reload
- name: nginx vh config symlink
  file:
    state: link
    src: /etc/nginx/sites-available/clash_dashboard.conf
    dest: /etc/nginx/sites-enabled/clash_dashboard.conf

- name: create vh root dir
  file:
    path: "{{root}}"
    state: directory

- name: chk zip exists
  stat:
    path: /tmp/clash_dashboard.zip
  register: zip_exists
# tasks file for clash-dashboard
- name: deploy dist.zip
  when: not zip_exists.stat.exists
  block:
  - name: copy
    copy:
      src: dist.zip
      dest: /tmp/clash_dashboard.zip
  - name: create tempdir
    tempfile:
      state: directory
    register: _tmpdir
  - name: unzip
    unarchive:
      remote_src: yes
      src: /tmp/clash_dashboard.zip
      dest: "{{_tmpdir.path}}"
  - name: sync     
    ansible.posix.synchronize:
      src: "{{_tmpdir.path}}/dist/"
      dest: "{{root}}/"
    delegate_to: "{{inventory_hostname}}"
  - name: remove the temporary file
    ansible.builtin.file:
      path: "{{ _tmpdir.path }}"
      state: absent
    when: _tmpdir.path is defined
