---
  - name: apt-transport-https
    apt:
      name: apt-transport-https
      state: latest

  - name: ca-certificates
    apt:
      name: ca-certificates
      state: latest

  - name: add docker repo gpg
    copy:
      src: docker.gpg
      dest: /etc/apt/trusted.gpg.d/docker.gpg

  - name: add docker repo file
    apt_repository:
      repo: deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/ubuntu {{ ansible_distribution_release }} stable
      filename: docker
      update_cache: yes
      state: present

  - name: install docker-ce latest version
    apt:
      name: docker-ce=17.06.2~ce-0~ubuntu
      state: present
    tags:
      - docker-ce-install
      
