---
#### general parameters
uninstall: false
systemd_name: rocketmq-exporter
systemd_short_name: rme
version: 0.0.2
archive_file: "rocketmq-exporter-{{version}}-SNAPSHOT-exec.jar"
unpacked_dirname: ""
urlpath: ""
# set single_exec_deploy true only when deploy single executable file , normaly we deploy a zip, tgz or tar.gz etc.
single_exec_deploy: true
download_dest: "/tmp/{{archive_file}}"
home: "/data/{{systemd_name}}/{{version}}"
user: "app_user"
group: "app_group"
# define ExecStart and ExecStop in systemd unit file
java_home: ""
service_state: started
exec_file: "{{home}}/{{archive_file}}"
exec_start: "{{java_home}}/bin/java -jar {{home}}/{{archive_file}}"
exec_stop: ""
# systemd restart policy
restart: "on-failure"
home_subdirs: []
# - bin
# - var
# - etc
file_copies: []
# file_copies:
# - src: jmx_prometheus_javaagent-0.18.0.jar
#   dest: "{{home}}/bin/jmx_prometheus_javaagent-0.18.0.jar"

config_files:
- src: systemd.service
  dest: /etc/systemd/system/{{systemd_name}}.service
- src: "env"
  dest: "{{home}}/.env"