# 需要卸载应用时，通过命令行传递这个变量
# ansible-playbook pb.yaml -e uninstall=true
uninstall: false
# 是否跳过handler执行，默认配置修改后会通知handler完成服务重启，
# 可以通过设置为True来跳过handler执行
skip_handlers: false
user: app_user
group: app_group
# define service state after deloy
# possible values: started, stopped, restarted, reloaded
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html#parameter-state
service_state: started

systemd_name: "kibana"
# used for service ctl alias commands
# for example {{systemd_name_short}}status -> systemctl status {{systemd_name}}.service
systemd_short_name: "kbn"
version: 7.17.22
archive_file: "kibana-{{version}}-linux-x86_64.tar.gz"
download_dest: "/tmp/{{archive_file}}"
# archive_file解压后的目录名称
unpacked_dirname: kibana-{{version}}-linux-x86_64
home: "/data/{{systemd_name}}/{{version}}"
# define ExecStart and ExecStop in systemd unit file
exec_start: "{{home}}/bin/kibana"
exec_stop: ""
# systemd restart policy
systemd_restart: "on-failure"
home_subdirs: []

# 拷贝额外文件到远程主机，一般不需要
file_copies: []
# file_copies:
# - src: jmx_prometheus_javaagent-0.18.0.jar
#   dest: "{{home}}/bin/jmx_prometheus_javaagent-0.18.0.jar"
config_files:
- src: systemd.service
  dest: /etc/systemd/system/{{systemd_name}}.service
- src: "env"
  dest: "{{home}}/.env"
- src: kibana.yml
  dest: "{{home}}/config/kibana.yml"


## kibana.yml
# Specifies the address to which the Kibana server will bind.
server_host: 0.0.0.0
# The Kibana server's name.  This is used for display purposes.
server_name: ""
# server.publicBaseUrl 最终用户访问 Kibana 的公开可用 URL
# 必须包含协议、主机名、端口（如果与 http 和 https 的默认值不同，分别为 80 和 443）
server_publicBaseUrl:
# elasticsearch.hosts
elasticsearch_hosts: ["http://localhost:9200"]
elasticsearch_username: "kibana_system"
elasticsearch_password: ""
elasticsearch_ssl_certificateAuthorities: []
