---
- name: stop service
  systemd:
    name: "{{systemd_name}}"
    state: stopped

- name: remove home dir
  file:
    path: "{{home}}"
    state: absent

- name: remove systemd unit file
  file:
    path: "{{item}}/{{systemd_name}}.service"
    state: absent
  loop:
  - "/etc/systemd/system"
  - "/lib/systemd/system"
  - "/usr/lib/systemd/system"

- name: remove {{item}} shortcuts commands
  blockinfile:
    path: "/home/{{user}}/.bashrc"
    marker: "# {{item}} svcctl {mark} ANSIBLE MANAGED BLOCK"
    block: |
      alias {{item}}status='sudo systemctl status {{item}}.service'
      alias {{item}}start='sudo systemctl start {{item}}.service'
      alias {{item}}stop='sudo systemctl stop {{item}}.service'
      alias {{item}}restart='sudo systemctl restart {{item}}.service'
      alias {{item}}log='journalctl -u {{item}}.service -f -n 200 -o cat'
    state: absent
  loop:
    - "{{systemd_name}}"